// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Reset() {
  return window['go']['backend']['App']['Reset']();
}

export function ToggleStatus() {
  return window['go']['backend']['App']['ToggleStatus']();
}
