// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Reset():Promise<backend.Board>;

export function ToggleStatus():Promise<boolean>;
