name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
        
    - name: Prepare frontend/dist
      run: mkdir -p frontend/dist && touch frontend/dist/.workaround

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Install Wails Build Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libgtk-3-dev libwebkit2gtk-4.0-dev pkg-config

    - name: Build
      run: wails build
