name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - platform:  'windows/amd64'
            os: 'windows-latest'
          - platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu

      - name: Build App
        if: runner.os != 'Linux'
        run: wails build -platform ${{ matrix.build.platform }}

      - name: Build Linux App
        if: runner.os == 'Linux'
        run: wails build -platform ${{ matrix.build.platform }} -tags webkit2_41

      - name: Add macOS perms
        if: runner.os == 'macOS'
        working-directory: .
        run: chmod +x build/bin/*/Contents/MacOS/*
        shell: bash

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts ${{ runner.os }}
          path: build/bin/*