name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    # - name: Install Wails Build Dependencies
    #   run: sudo apt-get update && sudo apt-get install -y build-essential libgtk-3-dev libwebkit2gtk-4.0-dev pkg-config

    - name: Build Linux/amd64
      run: wails build -platform linux/amd64

    - name: Build Windows/amd64
      run: wails build -platform windows/amd64

    - name: Build macOS/universal
      run: wails build -platform darwin/universal

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build artifacts
        path: build/bin/*
